(require 'package)
(push '("marmalade" . "http://marmalade-repo.org/packages/")
      package-archives )
(push '("melpa" . "http://melpa.milkbox.net/packages/")
      package-archives)
(package-initialize)
(require 'evil)
(evil-mode 1)
(require 'powerline-evil)
(powerline-center-evil-theme)
(load-theme 'base16-default-dark t)
